name: xtream-downloader
services:
  xtream-downloader:
    container_name: xtream-downloader
    deploy:
      resources:
        limits:
          memory: 4G
    environment:
      - TZ=Africa/Cairo
      - NODE_ENV=production
      - CONFIG_DIR=/config
    image: ghcr.io/devwael/xtream-downloader:latest
    ports:
      - protocol: tcp
        published: 9876
        target: 8080
    restart: unless-stopped
    volumes:
      - source: /mnt/Apps/xtream-downloader/config
        target: /config
        type: bind
      - source: /mnt/Storage/media/movies
        target: /movies
        type: bind
      - source: /mnt/Storage/media/cartoon
        target: /cartoon
        type: bind
x-portals:
  - host: 0.0.0.0
    name: Web UI
    path: /
    port: 9876
    scheme: http
